### ISSUE TITLE
Info about how to use it needed

### ISSUE THREAD

**Issue by tex** [sheenobu/nix-home#10]
Hello, I'm new to nixos and probably do not know something obvious, when I run nix-home script I get this error:

[milan@nixos nix-home]$ ./nix-home
nix-build -I NIXHOME -o /home/milan/.nix-home/current-home/ /home/milan || fail
warning: Nix search path entry ‘NIXHOME’ does not exist, ignoring
error: file ‘nixhome’ was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/milan/default.nix:2:13

**Comment by sheenobu** [comment]
You'll want to install this as a nix package. The wiki has an outdated version I should update:

```
{ stdenv, python, fetchFromGitHub }:
stdenv.mkDerivation rec {
  version = "0.2.2";
  name = "nix-home-${version}";

  src = fetchFromGitHub {
    rev = version;
    repo = "nix-home";
    owner = "sheenobu";
    sha256 = "09wdw4zddbi8p65mkba6w7awa6rm0dfhvj7miz47xhiw7sz0sqxp";
  };

  patchPhase = ''
    substituteInPlace nix-home --replace "NIXHOME" "$out/nix/lib"
  '';

  installPhase = ''
    # install binary
    mkdir -p $out/bin
    cp nix-home $out/bin
    chmod +x $out/bin/nix-home

    # install nix-home lib
    mkdir -p $out/nix
    cp -a lib $out/nix
  '';

  meta = {
    homepage = https://github.com/sheenobu/nix-home;
    description = "Per-user configuration management via Nix";
    licenses = [ stdenv.lib.license.mit ];
    platforms = stdenv.lib.platforms.unix;
    inherit version;
  };
}
```

**Comment by sheenobu** [comment]
Wiki is updated here https://github.com/sheenobu/nix-home/wiki/package.nix and the main README.md now has instructions for including it.
