### ISSUE TITLE
incorrect readme.txt

### ISSUE THREAD

**Issue by tex** [sheenobu/nix-home#11]
# Supported

nix-home, when invoked, automically builds ~/default.nix, which must define a derivation.

---

Well, it does not:

[milan@nixos ~]$ nix-home
No /home/milan/default.nix file found, refusing to run

**Comment by tex** [comment]
and sha256 in example.nix is not correct.

**Comment by sheenobu** [comment]
"Automatically builds it". You have to define it. It runs nix-build. The sha for mathiasbynens-dotfiles is wrong ? That's fine, don't use it.

**Comment by sheenobu** [comment]
Took out the 'automatically' part. "must define a derivation." is the important note. you have to do this yourself.

**Comment by tex** [comment]
Thanks ;-) Just want to ease any newcomer's life. If somebody uses your example he gets an error. No need for that...
